{"name": "加购物车", "status": "broken", "statusDetails": {"message": "TypeError: 'dict' object is not callable", "trace": "self = <testcases.usercenter.test_user.TestUser object at 0x10aa3ff10>\nusername = 17380900323, password = 123456\n\n    @allure.story(\"购物车相关\")\n    @allure.title(\"加购物车\")\n    @pytest.mark.parametrize(\"username,password\", get_data['user_login'])\n    def test_shopping_cart(self,username, password):\n        #登录接口\n        result = login(username, password)\n        token = result.body['token']\n    \n>       param = get_data()['shopping_cart']\nE       TypeError: 'dict' object is not callable\n\ntest_user.py:50: TypeError"}, "attachments": [{"name": "log", "source": "6077fcf3-6311-4caa-8a54-802321c5181e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "f57f5996-6b12-46ac-abd9-bd6f699e5aef-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "17380900323"}, {"name": "password", "value": "123456"}], "start": 1659104857813, "stop": 1659104858017, "uuid": "44a73256-978c-417f-9cae-328df28c19e6", "historyId": "078982f37d6fc574e848a2dd911995ae", "testCaseId": "6732b5a4ef5cebf11d6a36876a07be7c", "fullName": "testcases.usercenter.test_user.TestUser#test_shopping_cart", "labels": [{"name": "story", "value": "购物车相关"}, {"name": "feature", "value": "用户中心模块"}, {"name": "parentSuite", "value": "testcases.usercenter"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "shallowdeMacBook-Air.local"}, {"name": "thread", "value": "55464-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.usercenter.test_user"}]}